# Generated by Django 6.0.5 on 2026-06-07 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ani', '0016_character_image_focus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='看板名稱')),
                ('description', models.TextField(blank=True, verbose_name='看板簡介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='ani.ani', verbose_name='所屬作品')),
            ],
            options={
                'verbose_name': '看板',
                'verbose_name_plural': '看板列表',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='內容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agora_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='agora.board', verbose_name='看板')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='agora.post', verbose_name='回覆對象')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_posts', to='agora.post', verbose_name='所屬討論串')),
            ],
            options={
                'verbose_name': '貼文',
                'verbose_name_plural': '貼文列表',
                'ordering': ['created_at'],
            },
        ),
    ]
