# Generated by Django 6.0.5 on 2026-06-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='ani',
        ),
        migrations.AddField(
            model_name='board',
            name='anis',
            field=models.ManyToManyField(blank=True, related_name='boards', to='ani.ani', verbose_name='所屬作品'),
        ),
    ]
