# Generated by Django 6.0.5 on 2026-06-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0002_remove_board_ani_board_anis'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='name_ch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='看板名稱（簡中）'),
        ),
        migrations.AddField(
            model_name='board',
            name='name_zh',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='看板名稱（繁中）'),
        ),
    ]
