# Generated by Django 6.0.5 on 2026-06-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0003_board_name_ch_board_name_zh'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='agora_posts/', verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='內容'),
        ),
    ]
