# Generated by Django 6.0.5 on 2026-06-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0004_post_image_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='標題'),
        ),
    ]
