# Generated by Django 6.0.2 on 2026-03-24 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
            ],
            options={
                'verbose_name': '創作者',
                'verbose_name_plural': '創作者庫',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': '工作室/公司',
                'verbose_name_plural': '工作室/公司庫',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='標籤名稱')),
            ],
            options={
                'verbose_name': '標籤',
                'verbose_name_plural': '標籤庫',
            },
        ),
        migrations.CreateModel(
            name='Ani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='英文標題')),
                ('title_ch', models.CharField(blank=True, max_length=200, null=True, verbose_name='簡中標題')),
                ('title_zh', models.CharField(blank=True, max_length=200, null=True, verbose_name='繁中標題')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='海報封面')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='橫幅')),
                ('IMDb_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年分')),
                ('total_seasons', models.IntegerField(blank=True, null=True, verbose_name='總季數')),
                ('total_episodes', models.IntegerField(blank=True, null=True, verbose_name='總集數')),
                ('runtime', models.IntegerField(blank=True, null=True, verbose_name='單集時長')),
                ('imdb_stars', models.FloatField(blank=True, null=True, verbose_name='IMDb評分')),
                ('status', models.CharField(blank=True, choices=[('CROWDFUNDING', '募資中'), ('PILOT', '試播集'), ('UPCOMING', '即將上映'), ('GREENLIGHT', '確認製作'), ('ONGOING', '連載中'), ('PAUSED', '暫停更新'), ('FINISHED', '已完結'), ('CANCELLED', '已取消'), ('UNKNOWN', '未知狀態')], default='ONGOING', max_length=20, null=True, verbose_name='狀態')),
                ('rating', models.CharField(blank=True, max_length=50, null=True, verbose_name='分級')),
                ('description', models.TextField(blank=True, null=True, verbose_name='簡介')),
                ('creators', models.ManyToManyField(to='ani.creator', verbose_name='創作者')),
                ('studio', models.ManyToManyField(to='ani.studio', verbose_name='工作室/公司')),
                ('tags', models.ManyToManyField(to='ani.tag', verbose_name='標籤')),
            ],
            options={
                'verbose_name': '動畫',
                'verbose_name_plural': '動畫庫',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='名稱')),
                ('season', models.CharField(blank=True, max_length=20, null=True, verbose_name='季數')),
                ('number', models.CharField(max_length=20, verbose_name='集數')),
                ('release_time', models.DateTimeField(verbose_name='更新時間')),
                ('ani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='ani.ani')),
            ],
            options={
                'verbose_name': '集數',
                'verbose_name_plural': '劇集庫',
                'ordering': ['release_time'],
            },
        ),
    ]
