# Generated by Django 6.0.2 on 2026-02-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_ch', models.CharField(blank=True, max_length=200, null=True, verbose_name='title_zh')),
                ('title_zh', models.CharField(blank=True, max_length=200, null=True, verbose_name='title_ch')),
                ('IMDb_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='year')),
                ('total_seasons', models.IntegerField(blank=True, null=True, verbose_name='total_seasons')),
                ('total_episodes', models.IntegerField(blank=True, null=True, verbose_name='total_eps')),
                ('runtime', models.IntegerField(blank=True, null=True, verbose_name='runtime')),
                ('imdb_stars', models.FloatField(blank=True, null=True, verbose_name='imdb_stars')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='status')),
                ('rating', models.CharField(blank=True, max_length=50, null=True, verbose_name='rating')),
                ('studio', models.CharField(blank=True, max_length=100, null=True, verbose_name='studio')),
                ('creator', models.CharField(blank=True, max_length=100, null=True, verbose_name='creator')),
                ('tag', models.CharField(blank=True, max_length=200, null=True, verbose_name='tag')),
            ],
        ),
    ]
