# Generated by Django 6.0.2 on 2026-02-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
            ],
            options={
                'verbose_name': '創作者',
                'verbose_name_plural': '創作者庫',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
            ],
            options={
                'verbose_name': '工作室/公司',
                'verbose_name_plural': '工作室/公司庫',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='標籤名稱')),
            ],
            options={
                'verbose_name': '標籤',
                'verbose_name_plural': '標籤庫',
            },
        ),
        migrations.AlterModelOptions(
            name='ani',
            options={'verbose_name': '動畫', 'verbose_name_plural': '動畫庫'},
        ),
        migrations.RemoveField(
            model_name='ani',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='ani',
            name='tag',
        ),
        migrations.AlterField(
            model_name='ani',
            name='imdb_stars',
            field=models.FloatField(blank=True, null=True, verbose_name='IMDb評分'),
        ),
        migrations.AlterField(
            model_name='ani',
            name='rating',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='分級'),
        ),
        migrations.AlterField(
            model_name='ani',
            name='runtime',
            field=models.IntegerField(blank=True, null=True, verbose_name='單集時長'),
        ),
        migrations.AlterField(
            model_name='ani',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='狀態'),
        ),
        migrations.RemoveField(
            model_name='ani',
            name='studio',
        ),
        migrations.AlterField(
            model_name='ani',
            name='total_episodes',
            field=models.IntegerField(blank=True, null=True, verbose_name='總集數'),
        ),
        migrations.AlterField(
            model_name='ani',
            name='total_seasons',
            field=models.IntegerField(blank=True, null=True, verbose_name='總季數'),
        ),
        migrations.AlterField(
            model_name='ani',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='年分'),
        ),
        migrations.AddField(
            model_name='ani',
            name='creators',
            field=models.ManyToManyField(to='ani.creator', verbose_name='創作者'),
        ),
        migrations.AddField(
            model_name='ani',
            name='tags',
            field=models.ManyToManyField(to='ani.tag', verbose_name='標籤'),
        ),
        migrations.AddField(
            model_name='ani',
            name='studio',
            field=models.ManyToManyField(to='ani.studio', verbose_name='工作室/公司'),
        ),
    ]
