# Generated by Django 6.0.2 on 2026-05-23 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AniAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='別名')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='來源')),
                ('ani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='ani.ani')),
            ],
            options={
                'verbose_name': '別名',
                'verbose_name_plural': '別名庫',
            },
        ),
    ]
