# Generated by Django 6.0.2 on 2026-05-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0002_anialias'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMDbSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchlist_url', models.URLField(max_length=500, verbose_name='IMDb Watchlist URL')),
            ],
            options={
                'verbose_name': 'IMDb 同步設定',
                'verbose_name_plural': 'IMDb 同步設定',
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '等待中'), ('RUNNING', '執行中'), ('DONE', '完成'), ('ERROR', '錯誤')], default='PENDING', max_length=10)),
                ('progress', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '同步任務',
                'verbose_name_plural': '同步任務紀錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
