# Generated by Django 6.0.2 on 2026-02-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0002_creator_studio_tag_alter_ani_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ani',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='橫幅'),
        ),
        migrations.AddField(
            model_name='ani',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='海報封面'),
        ),
        migrations.AddField(
            model_name='studio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='ani',
            name='title',
            field=models.CharField(max_length=200, verbose_name='英文標題'),
        ),
        migrations.AlterField(
            model_name='ani',
            name='title_ch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='繁中標題'),
        ),
        migrations.AlterField(
            model_name='ani',
            name='title_zh',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='簡中標題'),
        ),
    ]
