# Generated by Django 6.0.2 on 2026-02-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0003_ani_banner_ani_poster_studio_logo_alter_ani_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ani',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='簡介'),
        ),
    ]
