# Generated by Django 6.0.2 on 2026-05-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0003_imdbsyncconfig_syncjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IMDbSyncConfig',
        ),
    ]
