# Generated by Django 6.0.5 on 2026-05-24 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0004_delete_imdbsyncconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ani.ani')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者評分',
                'verbose_name_plural': '使用者評分',
                'unique_together': {('user', 'ani')},
            },
        ),
    ]
