# Generated by Django 6.0.2 on 2026-02-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0004_ani_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ani',
            name='status',
            field=models.CharField(blank=True, choices=[('ONGOING', '連載中'), ('FINISHED', '已完結'), ('UPCOMING', '即將上映'), ('PAUSED', '暫停更新'), ('CANCELLED', '已取消'), ('CROWDFUNDING', '募資中'), ('UNKNOWN', '未知狀態')], default='ONGOING', max_length=20, null=True, verbose_name='狀態'),
        ),
        migrations.AlterField(
            model_name='ani',
            name='title_ch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='簡中標題'),
        ),
        migrations.AlterField(
            model_name='ani',
            name='title_zh',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='繁中標題'),
        ),
    ]
