# Generated by Django 6.0.2 on 2026-03-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0005_alter_ani_status_alter_ani_title_ch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='集數')),
                ('release_time', models.DateTimeField(verbose_name='更新時間')),
                ('ani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='ani.ani')),
            ],
            options={
                'verbose_name': '集數',
                'verbose_name_plural': '劇集庫',
                'ordering': ['release_time'],
            },
        ),
    ]
