# Generated by Django 6.0.5 on 2026-05-24 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0005_userrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ani.ani')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ani_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '評論',
                'verbose_name_plural': '評論',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'ani')},
            },
        ),
    ]
