# Generated by Django 6.0.5 on 2026-05-24 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0006_usercomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='ani',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='user',
        ),
        migrations.AlterField(
            model_name='ani',
            name='creators',
            field=models.ManyToManyField(blank=True, to='ani.creator', verbose_name='創作者'),
        ),
        migrations.AlterField(
            model_name='ani',
            name='studio',
            field=models.ManyToManyField(blank=True, to='ani.studio', verbose_name='工作室/公司'),
        ),
        migrations.AlterField(
            model_name='ani',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ani.tag', verbose_name='標籤'),
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ani.ani')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '評分與評論',
                'verbose_name_plural': '評分與評論',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'ani')},
            },
        ),
        migrations.DeleteModel(
            name='UserComment',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
