# Generated by Django 6.0.2 on 2026-03-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0006_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='季數'),
        ),
        migrations.AddField(
            model_name='episode',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='名稱'),
        ),
    ]
