# Generated by Django 6.0.5 on 2026-06-05 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0007_userreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
            ],
            options={
                'verbose_name': '人員',
                'verbose_name_plural': '人員庫',
            },
        ),
        migrations.CreateModel(
            name='AniPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CREATOR', '創作者'), ('VA', '聲優')], max_length=20)),
                ('ani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='ani.ani')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ani_roles', to='ani.person')),
            ],
            options={
                'verbose_name': '參與人員',
                'verbose_name_plural': '參與人員',
                'unique_together': {('ani', 'person', 'role')},
            },
        ),
        migrations.AddField(
            model_name='ani',
            name='person',
            field=models.ManyToManyField(blank=True, through='ani.AniPerson', to='ani.person', verbose_name='人員'),
        ),
    ]
