# Generated by Django 6.0.5 on 2026-06-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0009_migrate_creators_to_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ani',
            name='creators',
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
    ]
