# Generated by Django 6.0.5 on 2026-06-06 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0010_remove_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AniTrivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TRIVIA', '瑣事'), ('CLARIFY', '澄清'), ('BACKGROUND', '背景')], default='TRIVIA', max_length=20, verbose_name='分類')),
                ('body', models.TextField(verbose_name='內容')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('ani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia', to='ani.ani')),
            ],
            options={
                'verbose_name': '瑣事',
                'verbose_name_plural': '瑣事庫',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('name_zh', models.CharField(blank=True, max_length=100, null=True, verbose_name='中文名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='characters/', verbose_name='圖片')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('ani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='ani.ani')),
                ('va', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_voiced', to='ani.person', verbose_name='聲優')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色庫',
                'ordering': ['order', 'name'],
            },
        ),
    ]
