# Generated by Django 6.0.5 on 2026-06-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0011_character_aniTrivia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ani',
            name='trivia',
            field=models.TextField(blank=True, null=True, verbose_name='瑣事'),
        ),
        migrations.DeleteModel(
            name='AniTrivia',
        ),
    ]
