# Generated by Django 6.0.5 on 2026-06-07 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0016_character_image_focus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='系列名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='系列簡介')),
            ],
            options={
                'verbose_name': '系列',
                'verbose_name_plural': '系列庫',
            },
        ),
        migrations.AddField(
            model_name='ani',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='ani.series', verbose_name='所屬系列'),
        ),
    ]
