# Generated by Django 6.0.5 on 2026-06-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0017_series_ani_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='name_ch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='簡中名稱'),
        ),
        migrations.AddField(
            model_name='series',
            name='name_zh',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='繁中名稱'),
        ),
    ]
