# Generated by Django 6.0.5 on 2026-06-07 16:07

import ani.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ani', '0018_series_name_zh_ch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ani',
            name='videos',
            field=models.TextField(blank=True, help_text='每行一個 YouTube 或 Bilibili 連結，可選擇用「|」加上標題，例如：https://youtu.be/xxxx | PV預告', null=True, verbose_name='影片'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ani.models._char_image_path, verbose_name='圖片'),
        ),
    ]
