# Generated by Django 6.0.2 on 2026-03-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ani', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '會員', 'verbose_name_plural': '會員庫'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='following_anis',
            field=models.ManyToManyField(blank=True, related_name='followers', to='ani.ani', verbose_name='追番列表'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(blank=True, default='avatar_default.png', max_length=50, null=True, verbose_name='頭像'),
        ),
    ]
