# Generated by Django 6.0.5 on 2026-06-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_customuser_following_anis_and_more'),
        ('agora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='following_boards',
            field=models.ManyToManyField(blank=True, related_name='followers', to='agora.board', verbose_name='關注看板列表'),
        ),
    ]
